name: Sync Twitter to and from Mastodon
on:
  schedule:
    - cron: "24 */2 * * *"
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo itself
        uses: actions/checkout@v3
        with:
          path: job
      - name: Check out the synchronization code
        uses: actions/checkout@v3
        with:
          repository: klausi/mastodon-twitter-sync
          path: code
      - name: Install GPG to decrypt the configuration file
        run: sudo apt-get update && sudo apt-get install -y gnupg
      - name: Decrypt the configuration file
        run: gpg --quiet --batch --yes --passphrase="$GPG_PASSPHRASE" --decrypt job/mastodon-twitter-sync.toml.gpg > mastodon-twitter-sync.toml
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Install Rust
        run: |
          rustup toolchain install stable --profile minimal --no-self-update
          rustup default stable
        shell: bash
      - name: Cache executable
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: code
      - name: Execute synchronization
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --manifest-path=./code/Cargo.toml --release
      - name: Update post cache
        run: >
          cp ./post_cache.json ./job/ 2>/dev/null || :
      - name: Commit and push post cache
        uses: EndBug/add-and-commit@v7
        with:
          cwd: './job'
          add: post_cache.json
          default_author: github_actions
          message: Update post cache
